version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.3.0
    volumes:
      - /Users/faza/Documents/Project Latihan/grafana-loki-/loki-config.yaml:/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - /Users/faza/Documents/Project Latihan/grafana-loki-/promtail-local-config.yaml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - loki