version: "3"

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
    loki:
        image: grafana/loki:2.4.1
        command: -config.file=/etc/loki/loki-config.yaml
        ports:
            - "3100:3100"
        volumes:
            - ./:/loki
            - ./loki-config.yaml:/etc/loki/loki-config.yaml
        networks:
            - grafana-loki
            - promtail-loki

    promtail:
        depends_on:
            - loki
        image: grafana/promtail:latest
        volumes:
            - /var/log:/var/log
            - ./promtail-local-config.yaml:/etc/promtail/config.yaml
        command: -config.file=/etc/promtail/config.yaml
        networks:
            - promtail-loki

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:latest
        container_name: cadvisor
        privileged: true
        expose:
          - 8180
        devices:
            - /dev/kmsg:/dev/kmsg
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker:/var/lib/docker:ro
            #- /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
        restart: unless-stopped
        networks:
            - prometheus-cadvisor

    prometheus:
        image: prom/prometheus:latest
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus:/etc/prometheus
            - prometheus_data:/prometheus
        networks:
            - world
            - prometheus-cadvisor
            - grafana-prometheus
        command: >-
            --config.file=/etc/prometheus/prometheus.yml
            --storage.tsdb.path=/prometheus
            --web.console.libraries=/usr/share/prometheus/console_libraries
            --web.console.templates=/usr/share/prometheus/consoles

    nodeexporter:
        image: prom/node-exporter:v1.4.0
        container_name: nodeexporter
        volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
        command:
        - '--path.procfs=/host/proc'
        - '--path.rootfs=/rootfs'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
        restart: unless-stopped
        expose:
          - 9100
        networks:
            - prometheus-cadvisor

    alertmanager:
        image: prom/alertmanager:v0.24.0
        container_name: alertmanager
        volumes:
        - ./alertmanager:/etc/alertmanager
        command:
        - '--config.file=/etc/alertmanager/config.yml'
        - '--storage.path=/alertmanager'
        restart: unless-stopped
        expose:
        - 9093
        networks:
        - world

    grafana:
        depends_on:
            - loki
        image: grafana/grafana:latest
        volumes:
            - grafana_data:/var/lib/grafana
            - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
            - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
        ports:
            - "3000:3000"
        environment:
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: HelloWorld1234!@#
            GF_PATHS_PROVISIONING: '/etc/grafana/provisioning'
        networks:
            - world
            - grafana-loki
            - grafana-prometheus

networks:
    world:
    promtail-loki:
        internal: true
    grafana-loki:
        internal: true
    grafana-prometheus:
        internal: true
    prometheus-cadvisor:
        internal: true